<#
  Build-DemoWorkbooks.ps1 -- regenerate dist\demo\*.xlsm.

    .\tools\Build-DemoWorkbooks.ps1

  The demo ADD-INS are ordinary MSBuild projects and build with everything else:

    msbuild XRayXL.sln /p:Configuration=Release /p:Platform=x64

  which puts DemoFinance64.xll and DemoBehaviors64.xll under build\x64\Release\.

  The WORKBOOKS cannot be built that way. They are generated by driving Excel
  over COM and injecting VBA, so they need Excel installed AND "Trust access to
  the VBA project object model" (File > Options > Trust Center > Macro
  Settings). That is why the finished .xlsm files are committed, and why this
  runs only when the demo content itself changes. Opening and using them needs
  nothing but ordinary macro-enabling.
#>
$ErrorActionPreference = 'Stop'

$root  = Split-Path $PSScriptRoot -Parent
$wbOut = Join-Path $root 'dist\demo'
$built = Join-Path $root 'build\x64\Release'
New-Item -ItemType Directory -Force $wbOut | Out-Null

# The add-ins whose functions the saved formulas call. Build them first
# (msbuild XRayXL.sln) or the workbooks save with #NAME? cached in every cell.
# All three come straight from the build output, never from dist\ -- dist\ is
# what a RELEASE assembled, so generating against it would bake last release's
# behaviour into this release's workbooks. XRayXL itself is optional here: it
# is registered only so the Arm/Disarm buttons resolve while the book is made.
$registerXlls = @(
    (Join-Path $built 'DemoFinance\DemoFinance64.xll')
    (Join-Path $built 'DemoBehaviors\DemoBehaviors64.xll')
    (Join-Path $built 'XRayXL\XRayXL64.xll')
)

function Clear-ComRef($Refs) {
    # an unreleased COM wrapper keeps Excel alive after Quit
    foreach ($r in @($Refs)) {
        if ($r) { try { [void][Runtime.InteropServices.Marshal]::ReleaseComObject($r) } catch {} }
    }
}

# ---------------------------------------------------------------------------
# Generate the workbooks with Excel automation + VBA injection.
# ---------------------------------------------------------------------------
$xl = New-Object -ComObject Excel.Application
$xl.Visible = $false
$xl.DisplayAlerts = $false
try { $xl.EnableEvents = $false } catch {}   # don't fire events WHILE we build

# try/finally, so a failed build does not leave a hidden Excel running
try {
    # Load the demo XLLs so the saved formulas carry cached values (they resolve
    # again when the user loads the XLLs).
    foreach ($p in $registerXlls) {
        if (Test-Path $p) { try { [void]$xl.RegisterXLL($p) } catch { Write-Warning "RegisterXLL $(Split-Path $p -Leaf): $($_.Exception.Message)" } }
        else { Write-Warning "not built, so its formulas will cache as #NAME?: $p" }
    }

    function Save-Book($wb, $ws, $proj, $leaf) {
        # One-click Arm / Disarm on every sheet, so XRayXL can be driven without the
        # VBA editor. These call the tracer's XLL commands via Application.Run.
        $c = $proj.VBComponents.Add(1); $c.Name = 'XRay'
        $c.CodeModule.AddFromString(@'
Public Sub ArmXRay()
    On Error GoTo NoTracer
    Application.Run "XRayXL_SetTraceParam", "VBA", "DEPTH", "ALL"
    Dim ok: ok = Application.Run("XRayXL_Arm")
    MsgBox "XRayXL armed. Recalculate or press the demo button, then Disarm.", vbInformation, "XRayXL"
    Exit Sub
NoTracer:
    MsgBox "Could not reach XRayXL. Load it with File > Open on XRayXL64.xll," & vbCrLf & _
           "then press Arm again.", vbExclamation, "XRayXL"
End Sub

Public Sub DisarmXRay()
    On Error GoTo NoTracer
    Dim dropped: dropped = Application.Run("XRayXL_Disarm")
    On Error Resume Next
    Shell "explorer.exe """ & Environ$("TEMP") & "\XRayXL\TraceFiles""", vbNormalFocus
    MsgBox "XRayXL disarmed (" & dropped & " rows dropped)." & vbCrLf & _
           "The newest CSV in the opened folder is your trace.", vbInformation, "XRayXL"
    Exit Sub
NoTracer:
    MsgBox "XRayXL was not reachable.", vbExclamation, "XRayXL"
End Sub
'@)
        $a = $ws.Buttons().Add(460, 10, 120, 24); $a.Text = 'Arm XRayXL';      $a.OnAction = 'ArmXRay'
        $d = $ws.Buttons().Add(460, 40, 120, 24); $d.Text = 'Disarm + trace';  $d.OnAction = 'DisarmXRay'
        $path = Join-Path $wbOut $leaf
        Remove-Item $path -ErrorAction SilentlyContinue
        $wb.SaveAs($path, 52)      # 52 = xlOpenXMLWorkbookMacroEnabled (.xlsm)
        $wb.Close($false)
        Write-Host "  workbook -> $leaf"
        # release now rather than waiting for a GC before the next book
        Clear-ComRef @($a, $d, $c, $proj, $ws, $wb)
    }
    function Add-Module($proj, $name, $code) {
        $c = $proj.VBComponents.Add(1); $c.Name = $name       # 1 = standard module
        $c.CodeModule.AddFromString($code)
        Clear-ComRef @($c)
    }
    function Set-SheetCode($proj, $codeName, $code) {
        $comp = $proj.VBComponents.Item($codeName)
        $comp.CodeModule.AddFromString($code)
        Clear-ComRef @($comp)
    }

    # Prove VBA trust once, up front, with a clear message. The finally below quits Excel.
    try { $probe = $xl.Workbooks.Add(); [void]$probe.VBProject; $probe.Close($false) }
    catch { throw "Cannot inject VBA: enable File > Options > Trust Center > Macro Settings > 'Trust access to the VBA project object model', then re-run." }
    finally { Clear-ComRef @($probe) }

    # ===== 01 -- a VBA -> XLL calculation chain ================================
    $wb = $xl.Workbooks.Add()
    $ws = $wb.Worksheets.Item(1); $ws.Name = 'Book'
    $proj = $wb.VBProject
    Add-Module $proj 'CalcChain' @'
' A VBA UDF that calls a NESTED VBA helper -- one recalc, two VBA frames.
Public Function RiskWeighted(ByVal exposure As Double, ByVal rating As Long) As Double
    RiskWeighted = exposure * WeightFor(rating)
End Function
Private Function WeightFor(ByVal rating As Long) As Double
    Select Case rating
        Case 1: WeightFor = 0.2
        Case 2: WeightFor = 0.5
        Case Else: WeightFor = 1#
    End Select
End Function

' A VBA UDF that calls an XLL function (Application.Run) and adjusts it in VBA:
' the trace shows VBA -> XLL in one activation.
Public Function OptionBook(ByVal spot As Double) As Double
    Dim price As Double
    price = Application.Run("BlackScholes", spot, 100#, 1#, 0.05, 0.2)
    OptionBook = price * 100#          ' 100 contracts
End Function

' A button/macro target: dirty the volatile cells and recalculate everything.
Public Sub RunChain()
    Application.CalculateFull
End Sub
'@
    $ws.Range('A1').Value2 = 'A VBA->XLL calc chain. Load the demo XLLs + XRayXL, arm, then Recalculate.'
    $ws.Range('A3').Value2 = 'RiskWeighted (VBA+nested):'; $ws.Range('B3').Formula = '=RiskWeighted(1000000,3)'
    $ws.Range('A4').Value2 = 'OptionBook (VBA->XLL):';     $ws.Range('B4').Formula = '=OptionBook(100)'
    $ws.Range('A5').Value2 = 'BlackScholes (XLL):';        $ws.Range('B5').Formula = '=BlackScholes(100,100,1,0.05,0.2)'
    $ws.Range('A6').Value2 = 'SlowSum (slow XLL):';        $ws.Range('B6').Formula = '=SlowSum(2,3)'
    $ws.Range('A7').Value2 = 'Fibonacci (heavy XLL):';     $ws.Range('B7').Formula = '=Fibonacci(30)'
    $b = $ws.Buttons().Add(230, 15, 120, 28); $b.Text = 'Recalculate'; $b.OnAction = 'RunChain'
    $ws.Columns('A:B').AutoFit() | Out-Null
    Save-Book $wb $ws $proj '01_CalcChain.xlsm'
    Clear-ComRef @($b)

    # ===== 02 -- events (Change / Open / button) ==============================
    $wb = $xl.Workbooks.Add()
    $ws = $wb.Worksheets.Item(1); $ws.Name = 'Book'
    $proj = $wb.VBProject
    Add-Module $proj 'Events' @'
Public g_inChange As Boolean
Public Sub Recalc()
    ActiveSheet.Range("Trigger").Value = ActiveSheet.Range("Trigger").Value + 1
End Sub
Private Sub Helper()
    Dim t As Long: t = 1
End Sub
Public Sub OnChangeWork()
    Helper                       ' a nested VBA frame from the Change event
End Sub
'@
    Set-SheetCode $proj $ws.CodeName @'
Private Sub Worksheet_Change(ByVal Target As Range)
    If g_inChange Then Exit Sub
    g_inChange = True
    OnChangeWork
    g_inChange = False
End Sub
'@
    $proj.VBComponents.Item('ThisWorkbook').CodeModule.AddFromString(@'
Private Sub Workbook_Open()
    ThisWorkbook.Worksheets("Book").Range("Opened").Value = Now
End Sub
'@)
    $ws.Range('A1').Value2 = 'Events demo. Arm XRayXL, then edit the Trigger cell or press the button.'
    $ws.Range('A3').Value2 = 'Trigger (edit me):'; $ws.Range('B3').Name = 'Trigger'; $ws.Range('B3').Value2 = 0
    $ws.Range('A4').Value2 = 'Opened at:';         $ws.Range('B4').Name = 'Opened'
    $ws.Range('A5').Value2 = 'A volatile XLL:';    $ws.Range('B5').Formula = '=CallCounter()'
    $b = $ws.Buttons().Add(230, 15, 120, 28); $b.Text = 'Recalc (event)'; $b.OnAction = 'Recalc'
    $ws.Columns('A:B').AutoFit() | Out-Null
    Save-Book $wb $ws $proj '02_Events.xlsm'
    Clear-ComRef @($b)

    # ===== 03 -- error handling chains ========================================
    $wb = $xl.Workbooks.Add()
    $ws = $wb.Worksheets.Item(1); $ws.Name = 'Book'
    $proj = $wb.VBProject
    Add-Module $proj 'Errors' @'
' Outer catches; Middle only passes the error through; Thrower raises it.
' In the trace: Thrower=threw, Middle=unwound, Outer=handled.
Public Sub RunErrors()
    E_Outer
End Sub
Public Sub E_Outer()
    On Error GoTo Caught
    E_Middle
    Exit Sub
Caught:
    Dim n As Long: n = 1: n = 2      ' the handler resumed -> "handled"
End Sub
Public Sub E_Middle()
    E_Thrower
End Sub
Public Sub E_Thrower()
    Err.Raise 5, "Demo", "a deliberate error"
End Sub
'@
    $ws.Range('A1').Value2 = 'Error chains. Arm XRayXL, press Run, then read the outcome column of the trace.'
    $ws.Range('A3').Value2 = 'MightDivide(10,0) [XLL error]:'; $ws.Range('B3').Formula = '=MightDivide(10,0)'
    $ws.Range('A4').Value2 = 'SafeDivide(10,0) [XLL safe]:';   $ws.Range('B4').Formula = '=SafeDivide(10,0)'
    $b = $ws.Buttons().Add(280, 15, 140, 28); $b.Text = 'Run error chain'; $b.OnAction = 'RunErrors'
    $ws.Columns('A:B').AutoFit() | Out-Null
    Save-Book $wb $ws $proj '03_Errors.xlsm'
    Clear-ComRef @($b)

    # ===== 04 -- advanced: form+timer, recursion, class module ================
    $wb = $xl.Workbooks.Add()
    $ws = $wb.Worksheets.Item(1); $ws.Name = 'Book'
    $proj = $wb.VBProject
    Add-Module $proj 'Advanced' @'
' Recursion, a class, and a UserForm whose OnTime "timer" drives a recalc.
Public Sub RunAdvanced()
    Dim p As New Position
    p.Init 1000000, 3
    ThisWorkbook.Worksheets("Book").Range("Weighted").Value = p.Weighted

    ThisWorkbook.Worksheets("Book").Range("Tree").Value = WalkTree(6)

    Dim f As New DemoForm         ' UserForm_Initialize runs; Arm schedules the timer
    f.Arm
    Set f = Nothing
End Sub

Public Function WalkTree(ByVal depth As Long) As Long
    If depth <= 0 Then
        WalkTree = 1
    Else
        WalkTree = 1 + WalkTree(depth - 1) + WalkTree(depth - 1)
    End If
End Function

Public Sub TimerTick()
    ThisWorkbook.Worksheets("Book").Range("Ticked").Value = Now
    ThisWorkbook.Worksheets("Book").Calculate
End Sub
'@
    $cls = $proj.VBComponents.Add(2); $cls.Name = 'Position'   # 2 = class module
    $cls.CodeModule.AddFromString(@'
Private mExposure As Double
Private mRating As Long
Public Sub Init(ByVal exposure As Double, ByVal rating As Long)
    mExposure = exposure
    mRating = rating
End Sub
Public Property Get Weighted() As Double
    Weighted = mExposure * IIf(mRating <= 1, 0.2, IIf(mRating = 2, 0.5, 1#))
End Property
'@)
    $frm = $proj.VBComponents.Add(3); $frm.Name = 'DemoForm'    # 3 = UserForm
    $frm.CodeModule.AddFromString(@'
Private Sub UserForm_Initialize()
    Dim marker As Long: marker = 1
End Sub
Public Sub Arm()
    Application.OnTime Now, ThisWorkbook.Name & "!TimerTick"
End Sub
'@)
    $ws.Range('A1').Value2 = 'Advanced: recursion, a class, and a form+timer. Arm XRayXL, then press Run.'
    $ws.Range('A3').Value2 = 'Weighted (class):'; $ws.Range('B3').Name = 'Weighted'
    $ws.Range('A4').Value2 = 'WalkTree (recursion):'; $ws.Range('B4').Name = 'Tree'
    $ws.Range('A5').Value2 = 'Timer ticked at:'; $ws.Range('B5').Name = 'Ticked'
    $ws.Range('A7').Value2 = 'MakeSeries(6) [spilling XLL array]:'; $ws.Range('B7').Formula = '=MakeSeries(6)'
    $ws.Range('A9').Value2 = 'ThreadSafeSquare down a column [multi-threaded XLL]:'
    for ($i = 0; $i -lt 12; $i++) { $ws.Range("B$(10+$i)").Formula = "=ThreadSafeSquare($($i+1))" }
    $b = $ws.Buttons().Add(320, 15, 120, 28); $b.Text = 'Run advanced'; $b.OnAction = 'RunAdvanced'
    $ws.Columns('A:B').AutoFit() | Out-Null
    Save-Book $wb $ws $proj '04_Advanced.xlsm'
    Clear-ComRef @($b, $frm, $cls)
}
finally {
    # dropping the variable releases nothing: Excel is a ref-counted COM server
    if ($xl) {
        try { $xl.Quit() } catch {}
        Clear-ComRef @($xl)
    }
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
}

Write-Host "workbooks -> $wbOut"
Write-Host "done."
